// Generated by scripts/ascii-hands.py; edit the shapes there, not here.
// owners: h = human hand, r = robot hand, space = background
export const HANDS = {
"chars": [
"                                                                                                                       -====. .                                           ...----===",
"......                                                              ..........                                         .---= o===.                            ..----================",
"••••••••••••::::::.....                                         .::••••••••••••                                             .-====-              ...----============================",
"••••••••••••••••••••••••••••••::::::.....                  .::••••••••••••••••:                                           -=================- -=====================================",
"•••••••••••••••••••••••••••••••••••••••••••••••••::::::::•••••••••••••••:...                                 ..---- ========================- -=====================================",
"•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••::::::..                .====..===== o=======================- -=====================================",
"•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••::::.          ====- ==--.    .-===================- -========================----...",
"••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••::::••••••••••••••:.      ...         --======================- -===========---...",
"••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••:.  ...:••••••••:              -. ========================- .-...",
"....:::::::::::::•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••:        ......            -====o. -========-......",
"                                 .............::::::::•••••••••••••••••••••••••..:••••:.                        -=.  . .=-.-===-",
"                                                      .::•••••••••••••••••::••••. .••••:                      -=o=  ===o  .o-.",
"                                                          ..::::::::...:••:  :•••:.•••:                       .-..   --  .==.",
"                                                                        :••.  ••••:••:                             .=o-",
"                                                                         ..  .•••.",
"                                                                              .."
],
"owners": [
"                                                                                                                       rrrrrr r                                           rrrrrrrrrr",
"hhhhhh                                                              hhhhhhhhhh                                         rrrrr rrrrr                            rrrrrrrrrrrrrrrrrrrrrr",
"hhhhhhhhhhhhhhhhhhhhhhh                                         hhhhhhhhhhhhhhh                                             rrrrrrr              rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh                  hhhhhhhhhhhhhhhhhhhh                                           rrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh                                 rrrrrr rrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh                rrrrrrrrrrrr rrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh          rrrrr rrrrr    rrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh      rrr         rrrrrrrrrrrrrrrrrrrrrrrrr rrrrrrrrrrrrrrrrrr",
"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh  hhhhhhhhhhhhh              rr rrrrrrrrrrrrrrrrrrrrrrrrr rrrrr",
"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh        hhhhhh            rrrrrrr rrrrrrrrrrrrrrrr",
"                                 hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh                        rrr  r rrrrrrrrr",
"                                                      hhhhhhhhhhhhhhhhhhhhhhhhhhh hhhhhh                      rrrr  rrrr  rrrr",
"                                                          hhhhhhhhhhhhhhhhh  hhhhhhhhhh                       rrrr   rr  rrrr",
"                                                                        hhhh  hhhhhhhh                             rrrr",
"                                                                         hh  hhhhh",
"                                                                              hh"
],
"cols": 180,
"spark": [
100,
7
]
};
