# Generates lib/asciiHands.js: a human hand and a robot hand reaching for each
# other (after Michelangelo's Creation of Adam). Both are drawn as simple shapes,
# rasterised, then mapped to characters: the human in soft dots, the robot in
# machined plating with rivets at its joints.
#
#   python3 scripts/ascii-hands.py   (needs Pillow)
from PIL import Image, ImageDraw, ImageFilter
import math, json
W,H=1000,340
def capsule(d,p,q,r):
    (x1,y1),(x2,y2)=p,q; L=math.hypot(x2-x1,y2-y1); n=max(2,int(L/2))
    for i in range(n+1):
        t=i/n; x=x1+(x2-x1)*t; y=y1+(y2-y1)*t
        rr=r[0]+(r[1]-r[0])*t if isinstance(r,tuple) else r
        d.ellipse([x-rr,y-rr,x+rr,y+rr],fill=255)
def chain(d,pts,r):
    for a,b in zip(pts,pts[1:]): capsule(d,a,b,r)

# human (left): slimmer forearm, relaxed palm, index drooping toward the gap
human=Image.new('L',(W,H),0); h=ImageDraw.Draw(human)
capsule(h,(-60,150),(300,176),(40,30))
h.ellipse([285,134,425,226],fill=255)
chain(h,[(330,152),(382,130),(428,126)],(14,10))            # thumb
chain(h,[(412,160),(462,166),(506,176),(540,186)],(12,8))   # index
chain(h,[(408,180),(452,192),(474,214),(468,234)],(11,8))   # middle
chain(h,[(394,195),(430,210),(446,232),(440,248)],(10,7))   # ring
chain(h,[(376,207),(404,222),(412,240)],(9,6))              # little
human=human.filter(ImageFilter.GaussianBlur(2.5))

# robot (right): tapered palm, jointed fingers with gaps at each joint
robot=Image.new('L',(W,H),0); r=ImageDraw.Draw(robot)
joints=[]
def phalanges(pts,w):
    for a,b in zip(pts,pts[1:]):
        (x1,y1),(x2,y2)=a,b; L=math.hypot(x2-x1,y2-y1); ux,uy=(x2-x1)/L,(y2-y1)/L
        x1,y1,x2,y2=x1+ux*4,y1+uy*4,x2-ux*4,y2-uy*4          # leave a gap at each joint
        nx,ny=-uy*w,ux*w
        r.polygon([(x1+nx,y1+ny),(x2+nx,y2+ny),(x2-nx,y2-ny),(x1-nx,y1-ny)],fill=255)
    joints.extend(pts[1:-1])
# forearm with a gap at the wrist
r.polygon([(1060,88),(1060,150),(790,186),(790,128)],fill=255)
r.polygon([(780,126),(780,190),(690,198),(672,180),(668,142),(690,126)],fill=255)   # tapered palm
phalanges([(690,150),(642,152),(606,158),(574,166)],12)    # index: pointing left
phalanges([(682,174),(642,186),(620,208),(624,230)],10)    # middle, curled
phalanges([(694,188),(660,206),(648,228),(654,246)],9)     # ring, curled
phalanges([(712,196),(686,214),(680,234)],8)               # little
phalanges([(724,130),(694,108),(660,104)],10)              # thumb over the top

TOP,BOT=78,262                     # crop to the hands
human=human.crop((0,TOP,W,BOT)); robot=robot.crop((0,TOP,W,BOT))
COLS=180; ROWS=round((BOT-TOP)/((W/COLS)*1.1/0.6))   # keep the 0.6em x 1.1em character proportions
hg=human.resize((COLS,ROWS),Image.BOX).load(); rg=robot.resize((COLS,ROWS),Image.BOX).load()
# joints → cells, for rivets
jcells=set((round(x/W*COLS), round((y-TOP)/(BOT-TOP)*ROWS)) for x,y in joints)
lines=[]
for y in range(ROWS):
    row=[]
    for x in range(COLS):
        hv,rv=hg[x,y]/255,rg[x,y]/255
        if rv>0.3:
            if (x,y) in jcells: row.append(('r','o'))
            else: row.append(('r','=' if rv>0.8 else '-' if rv>0.55 else '.'))
        elif hv>0.15: row.append(('h','•' if hv>0.7 else ':' if hv>0.4 else '.'))
        else: row.append((' ',' '))
    lines.append(row)

# the spark goes in the narrowest gap between the two hands, halfway across it
best=None
for y,row in enumerate(lines):
    hs=[x for x,(k,_) in enumerate(row) if k=='h']; rs=[x for x,(k,_) in enumerate(row) if k=='r']
    if hs and rs and min(rs)>max(hs):
        gap=min(rs)-max(hs)
        if best is None or gap<best[0]: best=(gap,(max(hs)+min(rs))//2,y)
spark=(best[1],best[2])
chars=[''.join(c for _,c in row).rstrip() for row in lines]
owners=[''.join(k for k,_ in row)[:len(chars[i])] for i,row in enumerate(lines)]
# drop empty rows at the top and bottom
first=next(i for i,l in enumerate(chars) if l.strip()); last=max(i for i,l in enumerate(chars) if l.strip())
chars,owners=chars[first:last+1],owners[first:last+1]
spark=(spark[0], spark[1]-first)
with open('lib/asciiHands.js','w') as f:
    f.write('// Generated by scripts/ascii-hands.py; edit the shapes there, not here.\n')
    f.write('// owners: h = human hand, r = robot hand, space = background\n')
    f.write('export const HANDS = ' + json.dumps({'chars': chars, 'owners': owners, 'cols': COLS, 'spark': spark}, ensure_ascii=False, indent=0) + ';\n')
print('wrote lib/asciiHands.js', COLS, 'x', ROWS, 'spark at', spark)
